export const routes = {
  home: () => '/' as const,
  profile: () => '/profile' as const,
  goingOut: () => '/going-out' as const,
  orders: () => '/orders' as const,
  orderHistory: () => '/order-history' as const,
  messages: () => '/messages' as const,
  earnings: () => '/earnings' as const,
  settings: () => '/settings' as const,
  report: () => '/report' as const,
  createRequest: () => '/request/create' as const,
  requestDetails: (id: string) => `/request/${id}` as const,
  chat: (id: string) => `/chat/${id}` as const,
  orderStatus: (id: string) => `/order/${id}` as const,
  cravings: () => '/cravings' as const,
  createCraving: () => '/craving/create' as const,
  cravingDetail: (id: string) => `/craving/${id}` as const,
};